name: Auto Pull

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger webhook
      run: |
        curl -X POST http://45.84.16.160:5000/webhook -H "Content-Type: application/json" -d '{}'