name: Auto Pull and Run on Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger server script
        env:
          SERVER_IP: 10.36.5.44
          SERVER_USER: pam_golive
          SERVER_PATH: /home/pam_golive/test-CI-CD
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
          cd $SERVER_PATH &&
          git pull origin main &&
          python3 hello.py
          "
