name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm test

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger webhook
      run: |
        curl -X POST -H "Content-type: application/json" --data "{}" http://10.36.5.44:5000/webhook
