---
name: Auto Pull
on:
  push:
    branches:
      - main
jobs:
  test-connecton:
    runs-on: ubuntu-latest
    steps:
      - name: Test Network Connectivity
        run: |
          python hello.py
