---
name: Auto Pull
on:
  push:
    branches:
      - main
jobs:
  test-connecton:
    runs-on: ubuntu-latest
    steps:
      - name: Test Network Connectivity
        run: |
          ping -c 4 10.36.5.44
