name: CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger webhook
      run: |
        curl -X POST -H "Content-type: application/json" --data "{}" http://10.36.5.44:5000/webhook
