name: Deploy on Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger server pull
        run: |
          ssh -o StrictHostKeyChecking=no pam_golive@10.36.5.44 "
          cd /path/to/your/repo &&
          git pull origin main &&
          python3 hello.py
          "
