name: Auto Pull

on:
  push:
    branches:
      - main

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test Network Connectivity
        run: python hello.py
