name: Auto Pull

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger webhook
      run: |
        curl -X POST http://10.36.5.44:5000/webhook -H "Content-Type: application/json" -d '{}'